/**
 * Adaptive EMA Strategy v4 - 4H Configuration
 */

#ifndef ADAPTIVE_EMA_V4_CONFIG_4H_H
#define ADAPTIVE_EMA_V4_CONFIG_4H_H

#define USE_PERCENT_RANGE_4H

#define EMA_FAST_BASE_4H 9
#define EMA_SLOW_BASE_4H 21
#define ADX_LENGTH_4H 14
#define ADX_THRESHOLD_4H 20.0
#define RSI_LENGTH_4H 14
#define RSI_BUY_MAX_4H 70.0
#define RSI_SELL_MIN_4H 30.0
#define EFFICIENCY_LOOKBACK_4H 10

#define SEARCH_PERCENT_EMA_FAST_BASE_4H 0.4
#define SEARCH_PERCENT_EMA_SLOW_BASE_4H 0.3
#define SEARCH_PERCENT_ADX_LENGTH_4H 0.3
#define SEARCH_PERCENT_ADX_THRESHOLD_4H 0.3
#define SEARCH_PERCENT_RSI_LENGTH_4H 0.3
#define SEARCH_PERCENT_RSI_BUY_MAX_4H 0.15
#define SEARCH_PERCENT_RSI_SELL_MIN_4H 0.3
#define SEARCH_PERCENT_EFFICIENCY_LOOKBACK_4H 0.4

#endif // ADAPTIVE_EMA_V4_CONFIG_4H_H
