/**
 * Adaptive EMA Strategy v4 - 1D Configuration
 */

#ifndef ADAPTIVE_EMA_V4_CONFIG_1D_H
#define ADAPTIVE_EMA_V4_CONFIG_1D_H

#define USE_PERCENT_RANGE_1D

#define EMA_FAST_BASE_1D 9
#define EMA_SLOW_BASE_1D 21
#define ADX_LENGTH_1D 14
#define ADX_THRESHOLD_1D 20.0
#define RSI_LENGTH_1D 14
#define RSI_BUY_MAX_1D 70.0
#define RSI_SELL_MIN_1D 30.0
#define EFFICIENCY_LOOKBACK_1D 10

#define SEARCH_PERCENT_EMA_FAST_BASE_1D 0.4
#define SEARCH_PERCENT_EMA_SLOW_BASE_1D 0.3
#define SEARCH_PERCENT_ADX_LENGTH_1D 0.3
#define SEARCH_PERCENT_ADX_THRESHOLD_1D 0.3
#define SEARCH_PERCENT_RSI_LENGTH_1D 0.3
#define SEARCH_PERCENT_RSI_BUY_MAX_1D 0.15
#define SEARCH_PERCENT_RSI_SELL_MIN_1D 0.3
#define SEARCH_PERCENT_EFFICIENCY_LOOKBACK_1D 0.4

#endif // ADAPTIVE_EMA_V4_CONFIG_1D_H
